version: '3'
services:
# kommentare
    postgres:
      image: postgres:11.5-alpine
      container_name: beispielDb
      ports:
        - "5430:5432"
      networks:
        - metatime
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin1
        - POSTGRES_DB=test
      volumes:
        - ./artifacts/scripts/0001/:/docker-entrypoint-initdb.d

networks:
  metatime:
    driver: bridge